[[lm_Sensors]]
arch = "aarch64"
git-tree-sha1 = "6f21f8ff6869e2ce4cecea64fdeb873b8dba38a4"
libc = "glibc"
os = "linux"

    [[lm_Sensors.download]]
    sha256 = "7fbd0c8c7657a7d21ab39fcaf68f68f7f9933a30df936a7a70862b27c4211dc0"
    url = "https://github.com/JuliaBinaryWrappers/lm_Sensors_jll.jl/releases/download/lm_Sensors-v3.5.0+1/lm_Sensors.v3.5.0.aarch64-linux-gnu.tar.gz"
[[lm_Sensors]]
arch = "aarch64"
git-tree-sha1 = "bd6603632bb91159ea034252fe343ef26f68b996"
libc = "musl"
os = "linux"

    [[lm_Sensors.download]]
    sha256 = "54ba942da323ffb175b5bd8aaa39569dd7fd3acb77764e91b4920a77d5650a27"
    url = "https://github.com/JuliaBinaryWrappers/lm_Sensors_jll.jl/releases/download/lm_Sensors-v3.5.0+1/lm_Sensors.v3.5.0.aarch64-linux-musl.tar.gz"
[[lm_Sensors]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "85b70c62650cec637c9d57f63bb4e4ebb4784db9"
libc = "glibc"
os = "linux"

    [[lm_Sensors.download]]
    sha256 = "30183495e409c00f8f8367224c0e88f1a53ba4cb6c94e3f9c46d0a6e2e54a587"
    url = "https://github.com/JuliaBinaryWrappers/lm_Sensors_jll.jl/releases/download/lm_Sensors-v3.5.0+1/lm_Sensors.v3.5.0.armv7l-linux-gnueabihf.tar.gz"
[[lm_Sensors]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "20fa78ddb29dcd364e60ebdcc3b3d4dca90d1457"
libc = "musl"
os = "linux"

    [[lm_Sensors.download]]
    sha256 = "a0a9170458146ca5acf4935c8b44cfe48eb504abe9f120500857a7d1313c2659"
    url = "https://github.com/JuliaBinaryWrappers/lm_Sensors_jll.jl/releases/download/lm_Sensors-v3.5.0+1/lm_Sensors.v3.5.0.armv7l-linux-musleabihf.tar.gz"
[[lm_Sensors]]
arch = "i686"
git-tree-sha1 = "55aa8eb732e4618c7f2cffc1163daef262d1e6ef"
libc = "glibc"
os = "linux"

    [[lm_Sensors.download]]
    sha256 = "fd5bdfa9f268a52c354262a950bacb4a92e15dae7f54f531b16064b53e284923"
    url = "https://github.com/JuliaBinaryWrappers/lm_Sensors_jll.jl/releases/download/lm_Sensors-v3.5.0+1/lm_Sensors.v3.5.0.i686-linux-gnu.tar.gz"
[[lm_Sensors]]
arch = "i686"
git-tree-sha1 = "04850a907f3aca418b11f66a8e9b838484b2b202"
libc = "musl"
os = "linux"

    [[lm_Sensors.download]]
    sha256 = "51e2f8340ee0f69a5cd0ae5eb7f89659e40ee86e2cb9d5a72a6d245ee8380420"
    url = "https://github.com/JuliaBinaryWrappers/lm_Sensors_jll.jl/releases/download/lm_Sensors-v3.5.0+1/lm_Sensors.v3.5.0.i686-linux-musl.tar.gz"
[[lm_Sensors]]
arch = "powerpc64le"
git-tree-sha1 = "91c5d451671bcb7b5e798f8bace5ad7cb829b341"
libc = "glibc"
os = "linux"

    [[lm_Sensors.download]]
    sha256 = "f458c8b6339228253f9e23afc90e972cf9cd1710abb56992c79a9c21497cb611"
    url = "https://github.com/JuliaBinaryWrappers/lm_Sensors_jll.jl/releases/download/lm_Sensors-v3.5.0+1/lm_Sensors.v3.5.0.powerpc64le-linux-gnu.tar.gz"
[[lm_Sensors]]
arch = "x86_64"
git-tree-sha1 = "cc0cb5301bc75f549f6eaf1f7a124329f9b73cf0"
libc = "glibc"
os = "linux"

    [[lm_Sensors.download]]
    sha256 = "1dd2cb14175358719e74216343fdacaf792a16fd0d9da40511022f4c75d3b520"
    url = "https://github.com/JuliaBinaryWrappers/lm_Sensors_jll.jl/releases/download/lm_Sensors-v3.5.0+1/lm_Sensors.v3.5.0.x86_64-linux-gnu.tar.gz"
[[lm_Sensors]]
arch = "x86_64"
git-tree-sha1 = "5fd9ba2734f9f92f345ab92e0555af7ef0950ca7"
libc = "musl"
os = "linux"

    [[lm_Sensors.download]]
    sha256 = "7a2081bdb75a089e646fde803446e505a0f4956994e61735c0cbf7fbe95de761"
    url = "https://github.com/JuliaBinaryWrappers/lm_Sensors_jll.jl/releases/download/lm_Sensors-v3.5.0+1/lm_Sensors.v3.5.0.x86_64-linux-musl.tar.gz"
